CREATE TABLE USERS
(
	ID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(50),
	PASSWORD VARCHAR(65536),
	EMAIL VARCHAR(100),
	CONSTRAINT PK_USER_ID PRIMARY KEY(ID)
);

CREATE TABLE WALLETS
(
	ID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(60) NOT NULL,
	"VALUE" NUMERIC(10, 2),
	CONSTRAINT PK_WALLET_ID PRIMARY KEY(ID)
);

CREATE TABLE USERS_WALLETS
(
	ID BIGINT AUTO_INCREMENT,
	USER_ID BIGINT,
	WALLET_ID BIGINT,
	CONSTRAINT PK_UW_ID PRIMARY KEY(ID),
	CONSTRAINT FK_UW_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FK_UW_WALLET_ID FOREIGN KEY(WALLET_ID) REFERENCES WALLETS(ID)
);

CREATE TABLE WALLET_ITEMS
(
	ID BIGINT AUTO_INCREMENT,
	WALLET_ID BIGINT,
	"DATE" DATE,
	"TYPE" VARCHAR(2),
	DESCRIPTION VARCHAR(500),
	"VALUE" NUMERIC(10, 2),
	CONSTRAINT PK_WI_ID PRIMARY KEY(ID),
	CONSTRAINT FK_WI_WALLET_ID FOREIGN KEY(WALLET_ID) REFERENCES WALLETS(ID)
);