CREATE TABLE USERS
(
	ID SERIAL,
	NAME VARCHAR(50),
	PASSWORD VARCHAR,
	EMAIL VARCHAR(100),
	PRIMARY KEY(ID)
);

CREATE TABLE WALLET
(
	ID SERIAL,
	NAME VARCHAR(60),
	"VALUE" NUMERIC(10, 2),
	PRIMARY KEY(ID)
);

CREATE TABLE USERS_WALLET
(
	ID SERIAL,
	WALLET INTEGER,
	USERS INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY(USERS) REFERENCES USERS(ID),
	FOREIGN KEY(WALLET) REFERENCES WALLET(ID)
);

CREATE TABLE WALLET_ITEMS
(
	ID SERIAL,
	WALLET INTEGER,
	"DATE" DATE,
	"TYPE" VARCHAR(2),
	DESCRIPTION VARCHAR(500),
	"VALUE" NUMERIC(10, 2),
	PRIMARY KEY(ID),
	FOREIGN KEY(WALLET) REFERENCES WALLET(ID)
);